path: D:\Coding\YOLO\cat-and-dog-detection\cat-and-dog-detection-yolo\data  #images & txt data path (Change the directory based on your working space)
train: images/train
val: images/val

names:
  0: cat
  1: dog